name: 💡 Enhancement request
description: New feature or change request
labels: [ enhancement ]
body:
  - type: markdown
    attributes:
      value: |
        This ticket is about suggestions for a feature or particular enhancement.
        Feedback about this form is appreciated.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
