version: "2"

run:
  # Allow multiple runners in CI
  allow-parallel-runners: true

# Specific linter settings
linters:
  default: all
  disable:
    # No forbidden deps
    - depguard
    # fmt print is explicitly allowed as a script
    - forbidigo
    # Comments do not require dot or capital
    - godot
    # Requires nl before return
    - nlreturn
    # Allow unused stuff, because it's could enabled easily
    - unused
    # requires whitespaces even though for statements and assignments are common or used within loops
    - wsl
    - wsl_v5
    # Allow inline error handling - if reasonable we don't need to make it explicit
    - noinlineerr
  settings:
    revive:
      confidence: 0.1
      enable-all-rules: true
      rules:
        # Ignore formatting errors
        - name: unhandled-error
          arguments:
            - fmt.Printf
        - name: add-constant
          arguments:
            # Allow -1 and empty strings for checks like LastIndex != -1
            - allowInts: 0,1
              allowStrs: '""'
        # Allow panics on this script
        - name: deep-exit
          disabled: true
        - name: line-length-limit
          arguments:
            # 80 line length is not necessary anymore for todays standard
            - 120
        - name: cognitive-complexity
          arguments:
            - 14
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
