run:
  # Set to container quota
  concurrency: 0
  timeout: 60s
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    # requires whitespaces even though for statements and assignments are common or used within loops
    - wsl
    # Requires nl before return
    - nlreturn
    # Allow unused stuff, because it's could enabled easily
    - unused
    # fmt print is explicitly allowed as a script
    - forbidigo
    # Comments do not require dot or capital
    - godot
    # No forbidden deps
    - depguard
    # Deprecated
    - exportloopref
    - execinquery
    - gomnd

# Specific linter settings
linters-settings:
  revive:
    enable-all-rules: true
    confidence: 0.1
    rules:
      # Ignore formatting errors
      - name: unhandled-error
        arguments:
          - "fmt.Printf"
      - name: add-constant
        arguments:
        # Allow -1 and empty strings for checks like LastIndex != -1
          - allowInts: "0,1"
            allowStrs: '""'
      # Allow panics on this script
      - name: deep-exit
        disabled: true
      # 80 line length is not necessary anymore for todays standard
      - name: line-length-limit
        arguments: [ 120 ]
      - name: cognitive-complexity
        arguments: [14]
